"""
Generation layer: takes real, retrieved CVE rows (a DataFrame from
retrieval.py) and produces two kinds of AI-assisted output:
 
1. summarize() -- plain-English explanation of a vulnerability, using the
   local PRETRAINED google/flan-t5-base model (or a fast template fallback
   controlled by VIGIL_USE_LLM_SUMMARIES). This is the "G" in RAG.
 
2. suggest_remediation() -- fix guidance. The STEP LIST is always
   deterministic/rule-based (reacts to attack_vector, privileges, and
   description keywords like buffer overflow/XSS/privilege escalation) --
   this never fails and never hallucinates. On top of that, an OPTIONAL
   richer "detail" explanation is generated by Groq's hosted LLM API,
   grounded strictly in the CVE's real facts and the rule-based steps
   themselves (preventing hallucination, same principle as RAG). If the
   Groq API key is missing, the network is down, or the call fails for any
   reason, "detail" is simply None and the plain step list is used instead
   -- reliability never depends on the API being available.
"""
 
import os
import re
import threading
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from groq import Groq
 
MODEL_NAME = "google/flan-t5-base"
MAX_INPUT_TOKENS = 512
MAX_OUTPUT_TOKENS = 200
USE_LLM_SUMMARIES = os.getenv("VIGIL_USE_LLM_SUMMARIES", "0").lower() in {"1", "true", "yes"}
 
GROQ_MODEL = "openai/gpt-oss-20b"  
GROQ_TIMEOUT_SECONDS = 8             # fail fast -- never hang a live demo waiting on the network
 
_tokenizer = None
_model = None
_model_lock = threading.Lock()
_groq_client = None
 
 
# ============================================================
# Flan-T5 (local, used for plain-English summaries)
# ============================================================
 
def _load_model():
    """Lazy-load so importing this module doesn't immediately pull the model into memory."""
    global _tokenizer, _model
    if _model is None:
        with _model_lock:
            if _model is None:
                tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
                model = AutoModelForSeq2SeqLM.from_pretrained(
                    MODEL_NAME, attn_implementation="eager"
                )
                model.eval()
                _tokenizer = tokenizer
                _model = model
    return _tokenizer, _model
 
 
def _operator_phrase(operator: str) -> str:
    return {
        "<": "earlier than",
        "<=": "up to and including",
        "==": "exactly",
        ">": "later than",
        ">=": "starting from",
    }.get(operator, operator)
 
 
def build_single_cve_prompt(row: pd.Series) -> str:
    """Turn ONE retrieved CVE row into a grounded prompt for the model to rephrase."""
    op_phrase = _operator_phrase(row["operator"])
    facts_sentence = (
        f"{row['cve_id']} is a {row['label']} severity vulnerability with a CVSS score of "
        f"{row['cvss']}. {row['description']} It can be exploited over the {row['attack_vector']} "
        f"attack vector and requires {row['privileges']} privileges. It affects {row['product']} "
        f"versions {op_phrase} {row['version']}."
    )
    return (
        "Rewrite the passage below as a short, natural, plain-English paragraph for a "
        "non-technical reader. Do not copy field labels, do not list facts line by line, "
        "and do not add any information that isn't in the passage.\n\n"
        f"Passage: {facts_sentence}\n\nRewritten paragraph:"
    )
 
 
def _generate(prompt: str) -> str:
    tokenizer, model = _load_model()
    inputs = tokenizer(
        prompt, return_tensors="pt", truncation=True, max_length=MAX_INPUT_TOKENS
    )
    with _model_lock:
        with torch.inference_mode():
            outputs = model.generate(
                **inputs,
                max_length=MAX_OUTPUT_TOKENS,
                num_beams=4,
                repetition_penalty=1.3,
                no_repeat_ngram_size=3,
            )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)
 
 
def _fast_summary(row: pd.Series) -> str:
    """Build a grounded summary without loading a model during a web request."""
    severity = row.get("label") or "UNRATED"
    cvss = row.get("cvss")
    score = f" with a CVSS score of {cvss}" if pd.notna(cvss) else ""
    vector = row.get("attack_vector") or "unknown"
    privileges = row.get("privileges") or "unknown"
    return (
        f"This is a {severity} severity vulnerability{score}. {row['description']} "
        f"It is associated with the {vector.lower()} attack vector and requires "
        f"{privileges.lower()} privileges."
    )
 
 
def summarize(results: pd.DataFrame, product: str, version: str) -> list[dict]:
    """
    Returns a list of {"cve_id": ..., "summary": ...} -- one entry per CVE,
    summarized separately. This plays to flan-t5-base's strengths: it's a
    small model and stays far more faithful to the facts on short, single-CVE
    prompts than when asked to condense many CVEs into one paragraph.
    """
    if results.empty:
        return [{
            "cve_id": None,
            "summary": f"No known vulnerabilities were found for {product} version {version}.",
        }]
 
    summaries = []
    for _, row in results.iterrows():
        summary = _generate(build_single_cve_prompt(row)) if USE_LLM_SUMMARIES else _fast_summary(row)
        summaries.append({"cve_id": row["cve_id"], "summary": summary})
    return summaries
 
 
# ============================================================
# Groq (hosted API, used ONLY to add optional detail to remediation)
# ============================================================
 
def _get_groq_client():
    """Lazy-init. Returns None if no API key is set -- callers must treat
    that as 'detail unavailable' and fall back to the rule-based steps."""
    global _groq_client
    if _groq_client is None:
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            return None
        _groq_client = Groq(api_key=api_key, timeout=GROQ_TIMEOUT_SECONDS)
    return _groq_client
 
 
def _present_value(value) -> str | None:
    """Return a non-empty dataset value, treating pandas nulls as absent."""
    if value is None or pd.isna(value):
        return None
    text = str(value).strip()
    return text or None


def _verified_facts(row: pd.Series) -> dict[str, str | None]:
    """Collect only facts that are actually present in the source row."""
    return {
        "cve_id": _present_value(row.get("cve_id")),
        "product": _present_value(row.get("product")),
        "affected_version": _present_value(row.get("version")),
        "operator": _present_value(row.get("operator")),
        "affected_component": _present_value(row.get("affected_component")),
        "vulnerability_type": _present_value(row.get("vulnerability_type")),
        "fixed_version": _present_value(row.get("fixed_version")),
        "vendor_remediation": _present_value(row.get("vendor_remediation")),
        "vendor_mitigation": _present_value(row.get("vendor_mitigation")),
        "description": _present_value(row.get("description")),
        "attack_vector": _present_value(row.get("attack_vector")),
        "privileges": _present_value(row.get("privileges")),
    }


def _facts_text(facts: dict[str, str | None]) -> str:
    """Render verified facts for the prompt without adding inferred values."""
    labels = (
        ("CVE", "cve_id"),
        ("Product", "product"),
        ("Affected version condition", "affected_version"),
        ("Affected component", "affected_component"),
        ("Vulnerability type", "vulnerability_type"),
        ("Fixed version", "fixed_version"),
        ("Vendor remediation", "vendor_remediation"),
        ("Vendor mitigation", "vendor_mitigation"),
        ("Description", "description"),
        ("Attack vector", "attack_vector"),
        ("Privileges required", "privileges"),
    )
    lines = []
    for label, key in labels:
        value = facts.get(key)
        if key == "affected_version" and value:
            operator = facts.get("operator") or "in"
            value = f"{operator} {value}"
        if value:
            lines.append(f"{label}: {value}")
        elif key in {"fixed_version", "vendor_remediation", "vendor_mitigation"}:
            lines.append(f"{label}: not provided by the dataset")
    return "\n".join(lines)


def build_remediation_detail_prompt(row: pd.Series, base_steps: list[str]) -> str:
    """
    Grounds the LLM strictly in the CVE's real facts and the already-correct
    rule-based steps, so it elaborates rather than invents.
    """
    facts = _verified_facts(row)
    facts_text = _facts_text(facts)
    steps_text = "\n".join(f"- {s}" for s in base_steps)
    return (
        "You are a security analyst writing a remediation note for this specific "
        "vulnerability. Using ONLY the verified facts and deterministic remediation "
        "below, write a detailed but concise explanation (3-5 sentences). Explain "
        "why the listed remediation applies to THIS CVE. If a fixed version, vendor "
        "remediation, or vendor mitigation is marked unavailable, say so explicitly "
        "instead of guessing. Do NOT invent patch versions, dates, components, "
        "mitigations, or unrelated security recommendations. Do NOT just repeat the "
        "action items verbatim -- explain the reasoning.\n\n"
        f"Verified CVE facts:\n{facts_text}\n\n"
        f"Deterministic remediation:\n{steps_text}\n\n"
        "Detailed remediation explanation:"
    )
 
 
def _generate_groq_detail(prompt: str):
    """Calls Groq's API. Returns None on ANY failure -- caller must fall back."""
    client = _get_groq_client()
    if client is None:
        return None
    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,   # low temperature -- factual, not creative
            max_tokens=250,
        )
        text = response.choices[0].message.content
        return text.strip() if text else None
    except Exception as e:
        print(f"[generate.py] Groq API call failed, falling back to rule-based only: {e}")
        return None


def _validate_groq_detail(detail: str | None, row: pd.Series) -> str | None:
    """Reject details that add versions or operational advice absent from facts."""
    if not detail:
        return None

    facts = _verified_facts(row)
    allowed_versions = {
        version
        for key in ("affected_version", "fixed_version")
        for version in re.findall(r"\b\d+(?:\.\d+){1,3}\b", facts.get(key) or "")
    }
    mentioned_versions = set(re.findall(r"\b\d+(?:\.\d+){1,3}\b", detail))
    if not mentioned_versions.issubset(allowed_versions):
        return None

    lower_detail = detail.lower()
    verified_text = " ".join(
        value.lower() for value in facts.values() if value
    )
    if (
        facts["affected_component"]
        and "component" in lower_detail
        and facts["affected_component"].lower() not in lower_detail
    ):
        return None
    if (
        facts["product"]
        and "product is" in lower_detail
        and facts["product"].lower() not in lower_detail
    ):
        return None
    if not facts["fixed_version"] and (
        "vendor fixed version" in lower_detail
        or "vendor remediation" in lower_detail
        or "vendor recommends" in lower_detail
    ):
        return None
    if not facts["vendor_mitigation"] and (
        "vendor mitigation is available" in lower_detail
        or "vendor-provided mitigation" in lower_detail
    ):
        return None
    unsupported_actions = (
        "sanitize input",
        "encode input",
        "content-security-policy",
        "rate limit",
        "rate-limit",
        "firewall",
        "vpn-only",
        "invalidate session",
        "least privilege",
        "monitor logs",
    )
    for action in unsupported_actions:
        if action in lower_detail and action not in verified_text:
            return None

    return detail.strip()


def suggest_remediation(results: pd.DataFrame, detailed: bool = True) -> list[dict]:
    """
    Returns a list of {"cve_id": ..., "remediation": [steps...], "detail": str|None}.
 
    "remediation" (the step list) is ALWAYS deterministic and based only on
    verified row facts. "detail" is an OPTIONAL richer explanation from Groq.
    If unavailable or contradictory, "detail" is None and the deterministic
    steps remain the complete fallback.
    """
    if results.empty:
        return []
 
    suggestions = []
    for _, row in results.iterrows():
        facts = _verified_facts(row)
        product = facts["product"] or "the affected product"
        affected_version = facts["affected_version"] or "the affected version"
        operator = facts["operator"] or "in the affected range"
        fixed_version = facts["fixed_version"]
        vendor_remediation = facts["vendor_remediation"]
        vendor_mitigation = facts["vendor_mitigation"]

        if fixed_version:
            primary = f"PRIMARY REMEDIATION: Upgrade {product} to {fixed_version} or later."
        elif vendor_remediation:
            primary = f"PRIMARY REMEDIATION: {vendor_remediation}"
        else:
            primary = (
                f"PRIMARY REMEDIATION: Upgrade {product} to a vendor-supported "
                f"release containing the security fix; an exact fixed version is "
                f"not provided for this CVE."
            )

        steps = [
            f"AFFECTED VERSION: {product} {operator} {affected_version}.",
            (
                f"VERIFIED CVE FACT: {facts['description']}"
                if facts["description"]
                else "VERIFIED CVE FACT: No vulnerability description is provided."
            ),
            primary,
        ]
        if vendor_mitigation:
            steps.append(f"TEMPORARY MITIGATION: {vendor_mitigation}")
        else:
            steps.append(
                "TEMPORARY MITIGATION: No vendor-provided mitigation is recorded "
                "for this CVE in the dataset."
            )
        steps.append(
            "DEFENSE-IN-DEPTH: Use only additional controls documented by the "
            "vendor advisory for this CVE; none are asserted by this dataset."
        )

        detail = None
        if detailed:
            prompt = build_remediation_detail_prompt(row, steps)
            detail = _validate_groq_detail(_generate_groq_detail(prompt), row)
 
        suggestions.append({
            "cve_id": row["cve_id"],
            "remediation": steps,
            "detail": detail,
        })
    return suggestions
 
 
if __name__ == "__main__":
    # Quick manual test: python generate.py
    from retrieval import load_data, find_vulnerabilities
 
    df = load_data()
    results = find_vulnerabilities(df, "pan-os", "8.1.20")
 
    print("--- Summaries ---")
    for item in summarize(results, "pan-os", "8.1.20"):
        print(f"{item['cve_id']}: {item['summary']}\n")
 
    print("--- Remediation ---")
    for item in suggest_remediation(results):
        print(f"{item['cve_id']}:")
        for step in item['remediation']:
            print(f"  - {step}")
        if item['detail']:
            print(f"  DETAIL: {item['detail']}")
        else:
            print(f"  DETAIL: (none -- Groq unavailable, using rule-based steps only)")
        print()
 